### ISSUE TITLE
Official release tarball is needed.

### ISSUE THREAD

**Issue by ghost** [osch/luced#2]
I read all the documentations from luced.de and i found the following:
"Official LucED releases will be distributed as tar.gz archives, based on the widely used GNU autotools build system." That's great, but when? And i didn't see a configure file in git tree, so I have no idea how to package it at the time of writing. Thanks for reading.

**Comment by osch** [comment]
Detailed instructions how to obtain tar.gz archive can be found in the documentation in the section [Building in a development sandbox](http://luced.de/?page=documentation#sec7), subsection [Build a distributable tar.gz archive](http://luced.de/?page=documentation#sec11), however I agree that I should provide an official tar.gz file.

**Comment by osch** [comment]
You can now find an official release tarball under http://luced.de/?page=download.
